monkey-team-3801/on-board

- .github/workflows/deploy-heroku.yaml
- src/server/routes/health-check.ts
- src/server/server.ts
Add some placeholder routes
Ping the health route after Heroku deploy. Timeout 5 minutes.
🐵🐒🙊🙉🙈
> Setup health checking in github actions

- README.md
yeah the boys
Very important update to readme.md
🐵🐒🙊🙉🙈
> Updated readme.md with new badges

- src/server/routes/chat.ts
Fix chat being laggy due to socketIO event emitting after database operations.
🐵🐒🙊🙉🙈
> Move socketIO event before database update

- src/client/chat/ChatContainer.tsx
- src/client/chat/ChatLog.tsx
- src/client/chat/Log.tsx
- src/client/hooks/useSocket.tsx
- src/client/hooks/useTransformingSocket.tsx
- src/client/io/index.ts
- src/client/io/socket.ts
- src/client/styles/App.less
- src/events.ts
- src/server/routes/chat.ts
- src/server/server.ts
- src/types.ts
Improve the current chat system.
- Socket events are now emitted on the frontend
- Private rooms have SocketIO rooms associated with each
- Improve chat style
- Quality of life improvements
🐵🐒🙊🙉🙈
> Improve chat style and functionality

- src/client/chat/ChatContainer.tsx
Input bar now clears when message is submitted
-   [ ] Remember to format your code! (`npm run prettier && npm run eslint`)
-   [ ] Remember to run the tests! (`npm run test`)
-   [ ] Don't forget comments and docstrings!
-   [ ] Is it a breaking change? Remember to mention that!
Fixed bug, input now clears in chat when message is sent. 
🐵🐒🙊🙉🙈
> Fixed bug where chat input remained when message sent

- src/client/AppProtectedRoutes.tsx
- src/client/announcements/CreateAnnouncementsForm.tsx
- src/client/chat/ChatContainer.tsx
- src/client/chat/ChatLog.tsx
- src/client/chat/Log.tsx
- src/client/components/ClassOpenIndicator.less
- src/client/components/ClassOpenIndicator.tsx
- src/client/components/SimpleDatepicker.tsx
- src/client/components/index.tsx
- src/client/home/UserHomeContainer.tsx
- src/client/rooms/ClassroomPageContainer.tsx
- src/client/rooms/CreateRoomPage.tsx
- src/client/rooms/PrivateRoomContainer.tsx
- src/client/rooms/ScheduleRoomFormContainer.tsx
- src/client/types.ts
- src/events.ts
- src/server/database/schema/Session.ts
- src/server/jobs/job-runner.ts
- src/server/routes/session.ts
- src/server/utils.ts
- src/types.ts
- Added ability to schedule classrooms
- Added event for when a class opens
- Classrooms and private rooms are displayed on the home page
🐵🐒🙊🙉🙈
> Classrooms

- src/client/hooks/useDynamicFetch.tsx
- src/client/types.ts
- src/client/user/LoginPage.tsx
- src/client/utils.ts
- src/server/routes/course.ts
- src/server/routes/session.ts
- src/server/routes/user.ts
- src/server/server.ts
Setup simple error handler for the routes.
Just call `next(new Error("error message"));` from your route to trigger the error route. The message will be sent to the frontend.
🐵🐒🙊🙉🙈
> Added simple error handling

- src/client/home/UserHomeContainer.tsx
- src/server/routes/session.ts
- src/types.ts
Fixed missing delete session for `classroomSessions`.
🐵🐒🙊🙉🙈
> Fix deleting classroom sessions

- src/server/routes/user.ts
Resolves #60 
Update login and registration status code to be in line with the HTTP spec.
- [BradF-99](https://github.com/BradF-99)
- [Assasindie](https://github.com/Assasindie)
🐵🐒🙊🙉🙈
> Use better login/registration request status codes

- src/client/user/LoginContainer.tsx
- src/client/utils.ts
Fixed login error message not being displayed.
🐵🐒🙊🙉🙈
> Fix login screen not displaying error messages

- src/client/AppProtectedRoutes.tsx
- src/client/chat/Chat.less
- src/client/chat/ChatContainer.tsx
- src/client/chat/Log.tsx
- src/client/hooks/useTransformingSocket.tsx
- src/client/rooms/ClassroomPageContainer.tsx
- src/client/rooms/PrivateRoomContainer.tsx
- src/client/rooms/containers/SessionContainer.tsx
- src/client/rooms/containers/SidePanelContainer.tsx
- src/server/database/schema/Session.ts
- src/server/routes/chat.ts
- src/server/routes/session.ts
- src/server/server.ts
- src/types.ts
Fixed some chat bugs caused by all the changes to sessions.
🐵🐒🙊🙉🙈
> Fix chat events not working and chats failing on breakout rooms

- src/client/announcements/CreateAnnouncementsForm.tsx
- src/client/classes/ClassroomDisplayContainer.tsx
- src/client/classes/EditClassroomModal.tsx
- src/client/components/SimpleDatepicker.tsx
- src/client/home/UserHomeContainer.tsx
- src/client/rooms/CreateClassroomContainer.tsx
- src/client/rooms/ScheduleRoomFormContainer.tsx
- src/client/rooms/components/ScheduleRoomForm.tsx
- src/client/rooms/components/index.tsx
- src/client/rooms/index.tsx
- src/client/utils.ts
- src/server/database/schema/Job.ts
- src/server/database/schema/Session.ts
- src/server/jobs/ScheduleHandler.ts
- src/server/jobs/job-runner.ts
- src/server/routes/job.ts
- src/server/routes/session.ts
- src/server/utils.ts
- src/types.ts
Allow room editing, refactor various forms and validation.
Resolves #110 
🐵🐒🙊🙉🙈
> Improved rooms

- src/client/rooms/ClassroomPageContainer.tsx
- src/server/routes/session.ts
Fixes notifications playing even when turned off. Also contains other various small fixes.
🐵🐒🙊🙉🙈
> Fixed notification playing when it shouldnt

- src/server/routes/filehandler.ts
- src/server/routes/session.ts
- src/server/server.ts
Fix some endpoints not ending their requests and hanging all other requests.
🐵🐒🙊🙉🙈
> Fix endpoints

- src/client/classes/ClassContainer.tsx
- src/client/classes/PrivateRoomDisplayContainer.tsx
- src/client/filehandler/UploadContainer.tsx
- src/client/responses/DisplayContainer.tsx
- src/client/responses/DisplayResultsContainer.tsx
- src/client/responses/MultipleChoiceResultsChart.tsx
- src/client/rooms/CreatePrivateRoomContainer.tsx
- src/client/rooms/components/BreakoutRoomModal.tsx
- src/client/rooms/containers/BreakoutRoomAllocationContainer.tsx
- src/client/rooms/containers/ParticipantsContainer.tsx
- src/server/routes/session.ts
Fix most things included in bens list.
- Add a link to the class page when making a private room
- Fix Breakout rooms stacking up
- Sort users by raised hands ( do it with tutors online etc)
- Delete all breakout rooms
- Added Y axis in view results
🐵🐒🙊🙉🙈
> Ben's list

- src/client/announcements/AnnouncementsContainer.tsx
- src/client/announcements/CreateAnnouncementsForm.tsx
- src/client/classes/ClassContainer.tsx
- src/client/classes/ClassesPageContainer.tsx
- src/client/classes/ClassroomDisplayContainer.tsx
- src/client/classes/EditClassroomModal.tsx
- src/client/classes/EditPrivateRoomModal.tsx
- src/client/classes/PrivateRoomDisplayContainer.tsx
- src/client/courses/EnrolFormContainer.tsx
- src/client/home/UpcomingClassesContainer.tsx
- src/client/home/UserHomeContainer.tsx
- src/client/rooms/CreateClassroomContainer.tsx
- src/client/rooms/CreatePrivateRoomContainer.tsx
- src/client/rooms/ScheduleRoomFormContainer.tsx
- src/client/rooms/components/CreatePrivateRoomForm.tsx
- src/client/rooms/components/ScheduleRoomForm.tsx
- src/server/database/schema/Job.ts
- src/server/database/schema/Session.ts
- src/server/jobs/ScheduleHandler.ts
- src/server/jobs/job-runner.ts
- src/server/routes/course.ts
- src/server/routes/job.ts
- src/server/routes/session.ts
- src/server/routes/utils.ts
- src/server/utils.ts
- src/types.ts
Remove upcoming classrooms being jobs, upcoming classrooms are now just classrooms with an additional property.
Remove the unnecessary calls to the `/courses` endpoint.
🐵🐒🙊🙉🙈
> Rework upcoming classroom and optimise api calls

- src/client/AppProtectedRoutes.tsx
- src/client/chat/Chat.less
- src/client/chat/ChatModal.tsx
- src/client/chat/ChatSession.tsx
- src/client/chat/components/UserList.tsx
- src/client/home/UserHomeContainer.tsx
- src/client/types.ts
Added filtering to chat users and improve various chat elements.
🐵🐒🙊🙉🙈
> Chat improvements

- src/client/AppProtectedRoutes.tsx
- src/client/announcements/AnnouncementEntry.tsx
- src/client/announcements/AnnouncementsContainer.tsx
- src/client/chat/ChatModal.tsx
- src/client/components/ProfilePicture.tsx
- src/client/home/Homepage.less
- src/client/home/UserHomeContainer.tsx
- src/client/home/containers/CourseDetailsContainer.tsx
- src/client/home/containers/CourseStaffList.tsx
- src/client/home/containers/UserInfoContainer.tsx
- src/client/home/containers/index.tsx
- src/client/rooms/components/UserDisplay.tsx
- src/client/utils.ts
- src/server/routes/course.ts
Added additional info tab which displays users associated with courses.
Added online status indicator to various profile pics.
Resolves #23 #96 (Finally)
🐵🐒🙊🙉🙈
> Additional info container

- src/server/routes/filehandler.ts
This fixes file deletion not working within classrooms.
🐵🐒🙊🙉🙈
> Fixed delete route not searching for classrooms

- src/client/rooms/ClassroomPageContainer.tsx
- src/client/rooms/components/BreakoutRoomListModal.tsx
- src/client/rooms/components/index.tsx
- src/client/rooms/containers/RoomGroupingContainer.tsx
New modal to see available breakout rooms for students.
🐵🐒🙊🙉🙈
> Added breakout rooms lists

- src/client/hooks/useMyPeer.tsx
- src/client/peer/peer.ts
- src/client/rooms/ClassroomPageContainer.tsx
- src/client/rooms/PrivateRoomContainer.tsx
- src/client/rooms/classroom.less
- src/client/rooms/components/Participants.tsx
- src/client/rooms/components/SelfStreamDisplay.tsx
- src/client/rooms/components/UserStreamDisplay.tsx
- src/client/rooms/containers/ParticipantsContainer.tsx
- src/client/rooms/containers/SidePanelContainer.tsx
- src/client/videostreaming/MyVideo.tsx
- src/client/videostreaming/RemotePeerVideo.tsx
- src/client/videostreaming/StreamVideo.tsx
Users with webcams now replace their static profile picture if enabled. Defaults back to the profile pic if the stream doesn't exist.
🐵🐒🙊🙉🙈
> Add streaming for participants with webcams

- package.json
- src/@types/react-fade-in/index.d.ts
- src/client/AppProtectedRoutes.tsx
- src/client/classes/ClassroomDisplayContainer.tsx
- src/client/classes/PrivateRoomDisplayContainer.tsx
- src/client/home/Homepage.less
- src/client/home/UpcomingClassesContainer.tsx
- src/client/home/UserHeaderJumbotron.tsx
- src/client/home/UserHomeContainer.tsx
- src/client/navbar/Navbar.less
- src/client/navbar/Navbar.tsx
- src/client/styles/App.less
- tsconfig.json
Added a header to the homepage which displays some basic information.
🐵🐒🙊🙉🙈
> Added header to homepage

- scripts/fetchCourse.js
Fetch course now checks for db named "monkprod" first, and then "test". If those 2 names are not found, then log error and exits.
🐵🐒🙊🙉🙈
> Fetch course 2

- src/client/courses/EnrolFormContainer.tsx
- src/client/home/UserHomeContainer.tsx
- src/client/timetable/calendar/Calendar.tsx
- src/client/user/profile/ProfileSettingsContainer.tsx
Fixed calendar not updating if user enrolment changes.
🐵🐒🙊🙉🙈
> Fix updating enrolment not updating calendar

- src/client/timetable/calendar/Calendar.less
- src/client/timetable/calendar/Calendar.tsx
- src/client/timetable/calendar/CalendarDay.less
- src/client/timetable/calendar/CalendarDay.tsx
- src/client/timetable/calendar/CalendarHeading.tsx
- src/client/timetable/calendar/Event.tsx
- src/client/timetable/calendar/UpcomingEventsContainer.tsx
Updated the style on the new calendar.
Finally resolves #17 
🐵🐒🙊🙉🙈
> Calendar styling

- src/client/canvas/Canvas.less
- src/client/canvas/DrawingCanvas.tsx
- src/client/rooms/PrivateRoom.less
- src/client/rooms/PrivateRoomContainer.tsx
layout the private room again.
🐵🐒🙊🙉🙈
> Improved private room
